language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
script:
  - ./gradlew build
after_success:
  - |
    if [ ! -z "$TRANSIFEX_PASSWORD" ]; then
      virtualenv ~/env
      source ~/env/bin/activate
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install --upgrade requests[security] urllib3
      python -m pip install --upgrade transifex-client
      echo -e "[https://www.transifex.com]\napi_hostname = https://api.transifex.com\nhostname = https://www.transifex.com\nusername = api\npassword = ${TRANSIFEX_PASSWORD}\n" > ~/.transifexrc
      tx --version
      tx push -s --no-interactive
    fi
after_failure:
  - cat app/build/reports/checkstyle.html
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
env:
  global:
   - secure: "kwyk4/ug9j5KdmR4DGp4vi6/BAhnYiFFlXeyptLR5CQ2+u+FNv588WdIFQ4loFlubsokkOjD9XZx8BQF0f47Agsr8FOPS/c+tSdXF9AL1mXj5jAhnrHJGmmyUBW3t8A1+JwxWTpo8WEvzeWZDYEPhxfbnYdGjoz8fpWO4srskBZKcsaSoGIXNZ1d7YBUtp6nqqOhiyaySjVn6etmbO3bghA3A8bCc+9U5CN5LBGLG256KNHFC4+0J86zopcC04bDBs6c4HecI03xB5BPhSKjuBNN3b2mAFznqYf9VqK+QEC1w71tNn0iL7bZiUw9/tvozE5xQ6krcTgK4xqXHS+g720RhYkib0TSrlDn2jfMAlJqshzzHT2lb2ofPEJpJg7C7Lmzbv4MtMnoFuNfAj1wmN0aszYkMUeYx72ku1TrNIvvMiJX3b0H8DAEZD6xN7JV9IUJjZ0BHv7CUj2e5Ya+wFnfbOWBuMIQP3XJw6JopRHOlsijTgQYQC3rkFHfARWQ4N4jjsAXR4AXxmqB4dMa+QiF6hkSE+O7S8sDuk5sCYB1KeTW/oaSo1fRbfYE1lE5sXAkX9KPtXw2/OjSnCANKheDSRzzgDzj3d9dQA0zOq7XRwEQ+GHJapoVAEMdPn0mYgOwVxxm6Fsbh/67xEf2AtM1MITQcLiH4/OBJhVaGGc="
before_install:
      - yes | sdkmanager "platforms;android-30" 
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "bfabiszewski/ulogger-android"
      description: "ulogger-android build submitted via Travis CI"
    notification_email: scan.coverity@fabiszewski.net
    build_command_prepend: rm -rf ./build
    build_command: ./gradlew -Dorg.gradle.jvmargs= --no-daemon assemble
    branch_pattern: master
